CREATE DATABASE ADMINFLOW
GO

USE ADMINFLOW
GO

/* =========================
   TABELA USUARIOS
========================= */
CREATE TABLE USUARIOS (
    IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    SENHAHASH VARCHAR(255) NOT NULL,
    DATACRIACAO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATAATUALIZACAO DATETIME2 NULL,
);
/* =========================
   TABELA CLIENTES
========================= */
CREATE TABLE CLIENTES (
    IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(30),
    EMAIL VARCHAR(150),
    DATACRIACAO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATAATUALIZACAO DATETIME2 NULL,

);


/* =========================
   TABELA VESTIDOS
========================= */
CREATE TABLE VESTIDOS (
    IDVESTIDO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TAMANHO VARCHAR(10), -- P, M, G
    COR VARCHAR(50),
    TEMA VARCHAR(100), -- JUNINA, LUXO, ETC
    PRECO_ALUGUEL DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'DISPONIVEL', -- DISPONIVEL, ALUGADO, MANUTENCAO
    IMAGEM_URL TEXT,
    DATACRIACAO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATAATUALIZACAO DATETIME2 NULL,
);

/* =========================
   TABELA VESTIDOS
========================= */

CREATE TABLE ALUGUEIS (
    IDALUGUEL INT IDENTITY(1,1) PRIMARY KEY,

    CLIENTE_ID INT NOT NULL,
    VESTIDO_ID INT NOT NULL,

    DATA_RETIRADA DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,

    VALOR DECIMAL(10,2),
    MULTA DECIMAL(10,2) DEFAULT 0,

    STATUS VARCHAR(50) DEFAULT 'RESERVADO', 
    -- RESERVADO, RETIRADO, DEVOLVIDO, ATRASADO
	
    DATACRIACAO DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    DATAATUALIZACAO DATETIME2 NULL,

    CONSTRAINT FK_CLIENTE
        FOREIGN KEY(CLIENTE_ID) 
        REFERENCES CLIENTES(IDCLIENTE)
        ON DELETE CASCADE,

    CONSTRAINT FK_VESTIDO
        FOREIGN KEY(VESTIDO_ID) 
        REFERENCES VESTIDOS(IDVESTIDO)
        ON DELETE CASCADE
);